import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";

import SideNav from "./ui/dashboard/sidenav";


const sans = Inter({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const mono = Roboto_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${sans.variable} ${mono.variable} antialiased`}>
                <div className="w-full flex-none md:w-64">
                    <SideNav />
                </div>
                {children}
            </body>
        </html>
    );
}