import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import SideNav from '@/app/ui/dashboard/sidenav';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="flex h-screen flex-col md:flex-row md:overflow-show">

            <div className="grow p-6 md:overflow-show md:p-12">{children}</div>
        </div>
    );
}